import type { HeroConfig } from './heroFactory';

// ---------------------------------------------------------------------------
// THE DESIGN SOURCE OF TRUTH. This is the file we iterate on during the art
// pass — edit a config, reload ?forge=1, judge the silhouette. See heroFactory.ts
// for the HeroConfig schema and parts.ts for the available body/head/headgear/
// weapon/accessory options.
//
// Tones are named here for readability; reuse the shared aurora palette where it
// fits and add folklore-specific tones as needed.
// ---------------------------------------------------------------------------

const T = {
  // forest / pelts
  furBrown: 0x6b4a2f,
  furDark: 0x3d2b1a,
  furBlack: 0x2a1d12,
  muzzle: 0x5a4632,
  bone: 0xe8edf2,
  skin: 0xd7a98c,
  // night / spectral
  cloakDark: 0x2b2540,
  night: 0x1c2541,
  violet: 0x9d4edd,
  skinShadow: 0x3a2f4a,
  ghostGreen: 0x2ec4b6,
  iceCyan: 0xcaf0f8,
  // rags / iron
  ragGrey: 0x6b6b78,
  iron: 0x4a4a55,
  palePurple: 0xc9c4d6,
  // wood / cloth
  wood: 0x8b5a2b,
  woodDark: 0x5e3b1c,
  slate: 0x3a506b,
  steel: 0xcaf0f8,
  plaidRed: 0xb5341f,
  // frost
  frost: 0xb8c6d9,
  frostMid: 0x7d8aa0,
  ashen: 0x9aa6b8,
  // ghost
  white: 0xe8edf2,
  ghostSkin: 0xeae6f0,
  // lutin
  lutinGreen: 0x3a7d44,
  ember: 0xff9f1c,
};

export const HEROES: HeroConfig[] = [
  {
    id: 'loup-garou',
    name: 'Loup-Garou',
    build: 'lg',
    origin: 'Forêt',
    role: 'Cogneur',
    blurb: 'Homme le jour, bête la nuit — il déchire ses proies.',
    palette: { primary: T.furBrown, secondary: T.furDark, accent: T.bone, skin: T.muzzle },
    body: 'beast',
    head: 'snout',
    headgear: 'none',
    weapon: 'claws',
    accessories: [],
  },
  {
    id: 'bonhomme-sept-heures',
    name: 'Bonhomme Sept-Heures',
    build: 'md',
    origin: 'Nuit',
    role: 'Mystique',
    blurb: 'Vient chercher les enfants pas couchés, sac sur l’épaule.',
    palette: { primary: T.cloakDark, secondary: T.night, accent: T.violet, skin: T.skinShadow },
    body: 'tapered',
    head: 'box',
    headgear: 'hood',
    weapon: 'none',
    accessories: ['sack'],
  },
  {
    id: 'feu-follet',
    name: 'Feu Follet',
    build: 'float',
    origin: 'Nuit',
    role: 'Mystique',
    blurb: 'Flamme errante des marais qui égare les voyageurs.',
    palette: { primary: T.ghostGreen, secondary: T.night, accent: T.iceCyan, skin: T.iceCyan },
    body: 'wisp',
    head: 'orb',
    headgear: 'none',
    weapon: 'none',
    accessories: ['glow'],
  },
  {
    id: 'la-corriveau',
    name: 'La Corriveau',
    build: 'md',
    origin: 'Nuit',
    role: 'Mystique',
    blurb: 'Pendue dans sa cage de fer, elle hante encore les chemins.',
    palette: { primary: T.ragGrey, secondary: T.iron, accent: T.violet, skin: T.palePurple },
    body: 'gown',
    head: 'skull',
    headgear: 'none',
    weapon: 'none',
    accessories: ['cage'],
  },
  {
    id: 'chasse-galerie',
    name: 'Chasse-Galerie',
    build: 'float',
    origin: 'Rivière',
    role: 'Mystique',
    blurb: 'Canot volant — pacte avec le diable pour rentrer au Jour de l’An.',
    palette: { primary: T.night, secondary: T.slate, accent: T.wood, skin: T.skin },
    body: 'tapered',
    head: 'round',
    headgear: 'tuque',
    weapon: 'none',
    accessories: ['canoe'],
  },
  {
    id: 'draveur',
    name: 'Draveur',
    build: 'md',
    origin: 'Rivière',
    role: 'Cogneur',
    blurb: 'Dompte les billots sur la rivière, pic à la main.',
    palette: { primary: T.night, secondary: T.slate, accent: T.ember, skin: T.skin },
    body: 'block',
    head: 'round',
    headgear: 'furcap',
    weapon: 'pike',
    accessories: ['lantern'],
  },
  {
    id: 'bucheron',
    name: 'Bûcheron',
    build: 'lg',
    origin: 'Forêt',
    role: 'Cogneur',
    blurb: 'Abat les pins centenaires d’un seul coup de hache.',
    palette: { primary: T.plaidRed, secondary: T.cloakDark, accent: T.steel, skin: T.skin },
    body: 'block',
    head: 'round',
    headgear: 'tuque',
    weapon: 'axe',
    accessories: ['plaid'],
  },
  {
    id: 'coureur-des-bois',
    name: 'Coureur des bois',
    build: 'md',
    origin: 'Forêt',
    role: 'Tireur',
    blurb: 'Trappeur nomade, ceinture fléchée et mousquet.',
    palette: { primary: T.woodDark, secondary: T.furDark, accent: T.plaidRed, skin: T.skin },
    body: 'tapered',
    head: 'round',
    headgear: 'furcap',
    weapon: 'musket',
    accessories: ['ceinture'],
  },
  {
    id: 'carcajou',
    name: 'Carcajou',
    build: 'sm',
    origin: 'Forêt',
    role: 'Cogneur',
    blurb: 'Petit, féroce, increvable — le glouton des bois.',
    palette: { primary: T.furBlack, secondary: T.furDark, accent: T.bone, skin: T.muzzle },
    body: 'beast',
    head: 'snout',
    headgear: 'none',
    weapon: 'claws',
    accessories: [],
  },
  {
    id: 'windigo',
    name: 'Windigo',
    build: 'lg',
    origin: 'Nuit',
    role: 'Cogneur',
    blurb: 'Géant famélique des grands froids, ramure de glace.',
    palette: { primary: T.frost, secondary: T.frostMid, accent: T.iceCyan, skin: T.ashen },
    body: 'gaunt',
    head: 'skull',
    headgear: 'antlers',
    weapon: 'claws',
    accessories: ['glow'],
  },
  {
    id: 'dame-blanche',
    name: 'Dame Blanche',
    build: 'float',
    origin: 'Rivière',
    role: 'Mystique',
    blurb: 'Noyée vêtue de blanc, elle flotte au bord de l’eau.',
    palette: { primary: T.white, secondary: T.iceCyan, accent: T.iceCyan, skin: T.ghostSkin },
    body: 'gown',
    head: 'round',
    headgear: 'veil',
    weapon: 'none',
    accessories: ['glow'],
  },
  {
    id: 'lutin',
    name: 'Lutin',
    build: 'sm',
    origin: 'Forêt',
    role: 'Tireur',
    blurb: 'Tresse la crinière des chevaux la nuit, pour le plaisir.',
    palette: { primary: T.lutinGreen, secondary: T.wood, accent: T.ember, skin: T.skin },
    body: 'tapered',
    head: 'round',
    headgear: 'pointyhat',
    weapon: 'none',
    accessories: ['ceinture'],
  },
];
